# Generated by Django 2.0.7 on 2018-12-05 17:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_model_name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('budget_model_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ModelExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_expense_name', models.CharField(max_length=30)),
                ('model_expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('budget_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_expense', to='managerapp.BudgetModel')),
            ],
            options={
                'ordering': ['model_expense_amount'],
            },
        ),
        migrations.CreateModel(
            name='ModelIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_income_name', models.CharField(max_length=30)),
                ('model_income_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('budget_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_income', to='managerapp.BudgetModel')),
            ],
            options={
                'ordering': ['model_income_amount'],
            },
        ),
    ]
