# Generated by Django 2.0.7 on 2018-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0004_auto_20181211_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexpense',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetincome',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
