# Generated by Django 2.0.7 on 2018-12-19 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managerapp', '0005_auto_20181211_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_slot_name', models.CharField(max_length=30)),
                ('model_slot_duration', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_model_name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=False)),
                ('time_model_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_model_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='modeltimeslot',
            name='time_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_model', to='managerapp.TimeModel'),
        ),
    ]
