# Generated by Django 2.0.7 on 2018-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0006_auto_20181219_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltimeslot',
            name='weekday',
            field=models.BooleanField(default=True),
        ),
    ]
