# Generated by Django 2.0.7 on 2018-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0007_modeltimeslot_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltimeslot',
            name='model_slot_duration',
            field=models.FloatField(),
        ),
    ]
