# Generated by Django 2.0.7 on 2018-12-21 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managerapp', '0009_auto_20181220_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
                ('weekday', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_time_slot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
